inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
Metrics/ClassLength:
  Enabled: false
