version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

defaults: &defaults #dir ./circleci
  docker:
    - image: circleci/ruby:2.7.1-node

jobs:
  build_test:
    <<: *defaults
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run: gem install bundler
      - run:
          name: install dependencies
          command: |-
            bundle install --without development production  --path vendor/bundle
            npm install
      - run:
          name: setup database
          command: bundle exec rails db:migrate
      - run:
          name: check rubucop validate
          command: bundle exe rubocop
      - run:
          name: test rspec
          command: bundle exec rspec spec
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master


